name: my_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.18.1 # Hoặc phiên bản mới nhất
  fl_chart: ^0.68.0 # <<--- THÊM DÒNG NÀY


  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  firebase_core: ^2.30.0
  http: ^1.1.0  # Để gọi API
  webview_flutter: ^4.0.0
  cloud_firestore: ^4.17.5
  cached_network_image: ^3.3.1
  firebase_auth: ^4.17.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0


flutter:
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
